### PR TITLE
fix(on-cordova): use proper fn signature when overriding

### LINKED ISSUE #83: deviceready does not fire in latest update
using `"ember-cordova": "0.1.11",` deviceready fires, but using this latest from github, it does not fire.

### PR DESCRIPTION
**Pull request by anulman**
fixes #83

### CODE REVIEW

File: addon/services/cordova.js [hunk 1]
```diff
@@ -63,11 +63,11 @@ export default Service.extend(Evented, {
     });
   },
 
-  on(event, handler) {
-    if (event === 'deviceready' && this._readyHasTriggered) {
-      run.join(handler);
+  on(name, target, method) {
+    if (name === 'deviceready' && this._readyHasTriggered) {
+      run.join(method);
```
Comment (runspired) [inline addon/services/cordova.js]: this should join both target and method

Comment (anulman) [inline addon/services/cordova.js]: Good catch
